# Конфигурационный файл для загрузчика видео
# Поместите этот файл в ту же папку, что и основной скрипт

# Основные настройки
download_settings:
  # Папка для загрузок (относительно скрипта)
  download_directory: "Downloads"

  # Максимальное количество одновременных загрузок
  max_concurrent_downloads: 3

  # Максимальный размер файла в MB (0 = без ограничений)
  max_file_size_mb: 500

  # Автоматическое создание субтитров
  write_subtitles: true
  write_auto_subtitles: false

# Настройки качества по умолчанию
quality_settings:
  # Максимальное разрешение видео
  max_video_height: 1080

  # Качество аудио для MP3
  audio_quality: "192"

  # Предпочитаемые кодеки
  preferred_video_codec: "h264"
  preferred_audio_codec: "aac"

# Настройки плейлистов
playlist_settings:
  # Максимальное количество видео в плейлисте
  max_playlist_items: 100

  # Создавать ли отдельные папки для плейлистов
  create_playlist_folders: true

  # Скачивать ли плейлисты по умолчанию
  download_playlists_by_default: false

# Настройки сети
network_settings:
  # Таймаут соединения (секунды)
  socket_timeout: 30

  # Размер чанка для загрузки (байты)
  http_chunk_size: 10485760  # 10MB

  # Количество попыток при ошибке
  retries: 5

  # Использовать ли IPv6
  prefer_ipv6: false

# Настройки логирования
logging_settings:
  # Уровень логирования (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"

  # Максимальный размер лог-файла (MB)
  max_log_file_size: 10

  # Количество резервных лог-файлов
  backup_count: 5

  # Логировать ли в консоль
  console_output: true

# Постобработка
postprocessing:
  # Конвертация видео
  convert_video_format: null  # null, "mp4", "webm", "mkv"

  # Нормализация аудио
  normalize_audio: false

  # Удаление исходного файла после конвертации
  keep_original: true

  # Добавление метаданных
  embed_metadata: true
  embed_thumbnail: false

# Фильтры и исключения
filters:
  # Минимальная длительность видео (секунды)
  min_duration: 0

  # Максимальная длительность видео (секунды, 0 = без ограничений)
  max_duration: 0

  # Исключить видео с определенными словами в названии
  exclude_keywords: []

  # Включить только видео с определенными словами
  include_keywords: []

# Уведомления
notifications:
  # Показывать системные уведомления
  system_notifications: false

  # Воспроизводить звук при завершении
  play_sound_on_complete: false

  # Email уведомления (требует настройки SMTP)
  email_notifications: false
  email_smtp_server: "smtp.gmail.com"
  email_smtp_port: 587
  email_username: ""
  email_password: ""
  email_recipient: ""